modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"

[[mods]]
modId="glazedresymmetry"
version="${file.jarVersion}"
displayName="Glazed ReSymmetry"
description='''
Adds blocks to make glazed terracotta tile nicely at odd tile widths. Updated to 1.18.2!

Based on https://imgur.com/gallery/INH2a and https://feedback.minecraft.net/hc/en-us/community/posts/360028840532-Glazed-Terracotta-Pillars-The-Key-to-infinite-Terracotta-Patterns- and https://github.com/Brandcraf06/Blockus
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"